// avmm_interconnect.v

// Generated using ACDS version 22.3 104

`timescale 1 ps / 1 ps
module avmm_interconnect (
		input  wire        afu_slave_m0_waitrequest,                     //                   afu_slave_m0.waitrequest
		input  wire [31:0] afu_slave_m0_readdata,                        //                               .readdata
		input  wire        afu_slave_m0_readdatavalid,                   //                               .readdatavalid
		output wire [0:0]  afu_slave_m0_burstcount,                      //                               .burstcount
		output wire [31:0] afu_slave_m0_writedata,                       //                               .writedata
		output wire [23:0] afu_slave_m0_address,                         //                               .address
		output wire        afu_slave_m0_write,                           //                               .write
		output wire        afu_slave_m0_read,                            //                               .read
		output wire [3:0]  afu_slave_m0_byteenable,                      //                               .byteenable
		output wire        afu_slave_m0_debugaccess,                     //                               .debugaccess
		input  wire        bbs_slave_m0_waitrequest,                     //                   bbs_slave_m0.waitrequest
		input  wire [63:0] bbs_slave_m0_readdata,                        //                               .readdata
		input  wire        bbs_slave_m0_readdatavalid,                   //                               .readdatavalid
		output wire [0:0]  bbs_slave_m0_burstcount,                      //                               .burstcount
		output wire [63:0] bbs_slave_m0_writedata,                       //                               .writedata
		output wire [23:0] bbs_slave_m0_address,                         //                               .address
		output wire        bbs_slave_m0_write,                           //                               .write
		output wire        bbs_slave_m0_read,                            //                               .read
		output wire [7:0]  bbs_slave_m0_byteenable,                      //                               .byteenable
		output wire        bbs_slave_m0_debugaccess,                     //                               .debugaccess
		input  wire        cxl_io_clk_clk,                               //                     cxl_io_clk.clk
		input  wire        cxl_io_rst_reset_n,                           //                     cxl_io_rst.reset_n
		input  wire        int_conn_clk_clk,                             //                   int_conn_clk.clk
		input  wire        int_conn_rst_reset_n,                         //                   int_conn_rst.reset_n
		output wire        cxl_io_master_s0_waitrequest,                 //               cxl_io_master_s0.waitrequest
		output wire [63:0] cxl_io_master_s0_readdata,                    //                               .readdata
		output wire        cxl_io_master_s0_readdatavalid,               //                               .readdatavalid
		input  wire [0:0]  cxl_io_master_s0_burstcount,                  //                               .burstcount
		input  wire [63:0] cxl_io_master_s0_writedata,                   //                               .writedata
		input  wire [31:0] cxl_io_master_s0_address,                     //                               .address
		input  wire        cxl_io_master_s0_write,                       //                               .write
		input  wire        cxl_io_master_s0_read,                        //                               .read
		input  wire [7:0]  cxl_io_master_s0_byteenable,                  //                               .byteenable
		input  wire        cxl_io_master_s0_debugaccess,                 //                               .debugaccess
		input  wire        cxl_io_slave_m0_waitrequest,                  //                cxl_io_slave_m0.waitrequest
		input  wire [31:0] cxl_io_slave_m0_readdata,                     //                               .readdata
		input  wire        cxl_io_slave_m0_readdatavalid,                //                               .readdatavalid
		output wire [0:0]  cxl_io_slave_m0_burstcount,                   //                               .burstcount
		output wire [31:0] cxl_io_slave_m0_writedata,                    //                               .writedata
		output wire [23:0] cxl_io_slave_m0_address,                      //                               .address
		output wire        cxl_io_slave_m0_write,                        //                               .write
		output wire        cxl_io_slave_m0_read,                         //                               .read
		output wire [3:0]  cxl_io_slave_m0_byteenable,                   //                               .byteenable
		output wire        cxl_io_slave_m0_debugaccess,                  //                               .debugaccess
		input  wire        cmb2avst_slave_m0_waitrequest,                //              cmb2avst_slave_m0.waitrequest
		input  wire [31:0] cmb2avst_slave_m0_readdata,                   //                               .readdata
		input  wire        cmb2avst_slave_m0_readdatavalid,              //                               .readdatavalid
		output wire [0:0]  cmb2avst_slave_m0_burstcount,                 //                               .burstcount
		output wire [31:0] cmb2avst_slave_m0_writedata,                  //                               .writedata
		output wire [23:0] cmb2avst_slave_m0_address,                    //                               .address
		output wire        cmb2avst_slave_m0_write,                      //                               .write
		output wire        cmb2avst_slave_m0_read,                       //                               .read
		output wire [3:0]  cmb2avst_slave_m0_byteenable,                 //                               .byteenable
		output wire        cmb2avst_slave_m0_debugaccess,                //                               .debugaccess
		output wire        debug_master_s0_waitrequest,                  //                debug_master_s0.waitrequest
		output wire [31:0] debug_master_s0_readdata,                     //                               .readdata
		output wire        debug_master_s0_readdatavalid,                //                               .readdatavalid
		input  wire [0:0]  debug_master_s0_burstcount,                   //                               .burstcount
		input  wire [31:0] debug_master_s0_writedata,                    //                               .writedata
		input  wire [31:0] debug_master_s0_address,                      //                               .address
		input  wire        debug_master_s0_write,                        //                               .write
		input  wire        debug_master_s0_read,                         //                               .read
		input  wire [3:0]  debug_master_s0_byteenable,                   //                               .byteenable
		input  wire        debug_master_s0_debugaccess,                  //                               .debugaccess
		input  wire        side_clock_hip_clk,                           //                 side_clock_hip.clk
		input  wire        side_reset_hip_reset_n,                       //                 side_reset_hip.reset_n
		input  wire        hip_reconfig_slave_m0_waitrequest,            //          hip_reconfig_slave_m0.waitrequest
		input  wire [7:0]  hip_reconfig_slave_m0_readdata,               //                               .readdata
		input  wire        hip_reconfig_slave_m0_readdatavalid,          //                               .readdatavalid
		output wire [0:0]  hip_reconfig_slave_m0_burstcount,             //                               .burstcount
		output wire [7:0]  hip_reconfig_slave_m0_writedata,              //                               .writedata
		output wire [23:0] hip_reconfig_slave_m0_address,                //                               .address
		output wire        hip_reconfig_slave_m0_write,                  //                               .write
		output wire        hip_reconfig_slave_m0_read,                   //                               .read
		output wire [0:0]  hip_reconfig_slave_m0_byteenable,             //                               .byteenable
		output wire        hip_reconfig_slave_m0_debugaccess,            //                               .debugaccess
		input  wire        usr_avmm_hip_reconfig_slave_m0_waitrequest,   // usr_avmm_hip_reconfig_slave_m0.waitrequest
		input  wire [7:0]  usr_avmm_hip_reconfig_slave_m0_readdata,      //                               .readdata
		input  wire        usr_avmm_hip_reconfig_slave_m0_readdatavalid, //                               .readdatavalid
		output wire [0:0]  usr_avmm_hip_reconfig_slave_m0_burstcount,    //                               .burstcount
		output wire [7:0]  usr_avmm_hip_reconfig_slave_m0_writedata,     //                               .writedata
		output wire [23:0] usr_avmm_hip_reconfig_slave_m0_address,       //                               .address
		output wire        usr_avmm_hip_reconfig_slave_m0_write,         //                               .write
		output wire        usr_avmm_hip_reconfig_slave_m0_read,          //                               .read
		output wire [0:0]  usr_avmm_hip_reconfig_slave_m0_byteenable,    //                               .byteenable
		output wire        usr_avmm_hip_reconfig_slave_m0_debugaccess,   //                               .debugaccess
		input  wire        cxl_compliance_slave_m0_waitrequest,          //        cxl_compliance_slave_m0.waitrequest
		input  wire [63:0] cxl_compliance_slave_m0_readdata,             //                               .readdata
		input  wire        cxl_compliance_slave_m0_readdatavalid,        //                               .readdatavalid
		output wire [0:0]  cxl_compliance_slave_m0_burstcount,           //                               .burstcount
		output wire [63:0] cxl_compliance_slave_m0_writedata,            //                               .writedata
		output wire [23:0] cxl_compliance_slave_m0_address,              //                               .address
		output wire        cxl_compliance_slave_m0_write,                //                               .write
		output wire        cxl_compliance_slave_m0_read,                 //                               .read
		output wire [7:0]  cxl_compliance_slave_m0_byteenable,           //                               .byteenable
		output wire        cxl_compliance_slave_m0_debugaccess           //                               .debugaccess
	);

	intel_rtile_cxl_top_cxltyp3_ed_cxltyp3ddr_avmm_interconnect_100_kentdoy avmm_interconnect (
		.afu_slave_m0_waitrequest                     (afu_slave_m0_waitrequest),                     //   input,   width = 1,                   afu_slave_m0.waitrequest
		.afu_slave_m0_readdata                        (afu_slave_m0_readdata),                        //   input,  width = 32,                               .readdata
		.afu_slave_m0_readdatavalid                   (afu_slave_m0_readdatavalid),                   //   input,   width = 1,                               .readdatavalid
		.afu_slave_m0_burstcount                      (afu_slave_m0_burstcount),                      //  output,   width = 1,                               .burstcount
		.afu_slave_m0_writedata                       (afu_slave_m0_writedata),                       //  output,  width = 32,                               .writedata
		.afu_slave_m0_address                         (afu_slave_m0_address),                         //  output,  width = 24,                               .address
		.afu_slave_m0_write                           (afu_slave_m0_write),                           //  output,   width = 1,                               .write
		.afu_slave_m0_read                            (afu_slave_m0_read),                            //  output,   width = 1,                               .read
		.afu_slave_m0_byteenable                      (afu_slave_m0_byteenable),                      //  output,   width = 4,                               .byteenable
		.afu_slave_m0_debugaccess                     (afu_slave_m0_debugaccess),                     //  output,   width = 1,                               .debugaccess
		.bbs_slave_m0_waitrequest                     (bbs_slave_m0_waitrequest),                     //   input,   width = 1,                   bbs_slave_m0.waitrequest
		.bbs_slave_m0_readdata                        (bbs_slave_m0_readdata),                        //   input,  width = 64,                               .readdata
		.bbs_slave_m0_readdatavalid                   (bbs_slave_m0_readdatavalid),                   //   input,   width = 1,                               .readdatavalid
		.bbs_slave_m0_burstcount                      (bbs_slave_m0_burstcount),                      //  output,   width = 1,                               .burstcount
		.bbs_slave_m0_writedata                       (bbs_slave_m0_writedata),                       //  output,  width = 64,                               .writedata
		.bbs_slave_m0_address                         (bbs_slave_m0_address),                         //  output,  width = 24,                               .address
		.bbs_slave_m0_write                           (bbs_slave_m0_write),                           //  output,   width = 1,                               .write
		.bbs_slave_m0_read                            (bbs_slave_m0_read),                            //  output,   width = 1,                               .read
		.bbs_slave_m0_byteenable                      (bbs_slave_m0_byteenable),                      //  output,   width = 8,                               .byteenable
		.bbs_slave_m0_debugaccess                     (bbs_slave_m0_debugaccess),                     //  output,   width = 1,                               .debugaccess
		.cxl_io_clk_clk                               (cxl_io_clk_clk),                               //   input,   width = 1,                     cxl_io_clk.clk
		.cxl_io_rst_reset_n                           (cxl_io_rst_reset_n),                           //   input,   width = 1,                     cxl_io_rst.reset_n
		.int_conn_clk_clk                             (int_conn_clk_clk),                             //   input,   width = 1,                   int_conn_clk.clk
		.int_conn_rst_reset_n                         (int_conn_rst_reset_n),                         //   input,   width = 1,                   int_conn_rst.reset_n
		.cxl_io_master_s0_waitrequest                 (cxl_io_master_s0_waitrequest),                 //  output,   width = 1,               cxl_io_master_s0.waitrequest
		.cxl_io_master_s0_readdata                    (cxl_io_master_s0_readdata),                    //  output,  width = 64,                               .readdata
		.cxl_io_master_s0_readdatavalid               (cxl_io_master_s0_readdatavalid),               //  output,   width = 1,                               .readdatavalid
		.cxl_io_master_s0_burstcount                  (cxl_io_master_s0_burstcount),                  //   input,   width = 1,                               .burstcount
		.cxl_io_master_s0_writedata                   (cxl_io_master_s0_writedata),                   //   input,  width = 64,                               .writedata
		.cxl_io_master_s0_address                     (cxl_io_master_s0_address),                     //   input,  width = 32,                               .address
		.cxl_io_master_s0_write                       (cxl_io_master_s0_write),                       //   input,   width = 1,                               .write
		.cxl_io_master_s0_read                        (cxl_io_master_s0_read),                        //   input,   width = 1,                               .read
		.cxl_io_master_s0_byteenable                  (cxl_io_master_s0_byteenable),                  //   input,   width = 8,                               .byteenable
		.cxl_io_master_s0_debugaccess                 (cxl_io_master_s0_debugaccess),                 //   input,   width = 1,                               .debugaccess
		.cxl_io_slave_m0_waitrequest                  (cxl_io_slave_m0_waitrequest),                  //   input,   width = 1,                cxl_io_slave_m0.waitrequest
		.cxl_io_slave_m0_readdata                     (cxl_io_slave_m0_readdata),                     //   input,  width = 32,                               .readdata
		.cxl_io_slave_m0_readdatavalid                (cxl_io_slave_m0_readdatavalid),                //   input,   width = 1,                               .readdatavalid
		.cxl_io_slave_m0_burstcount                   (cxl_io_slave_m0_burstcount),                   //  output,   width = 1,                               .burstcount
		.cxl_io_slave_m0_writedata                    (cxl_io_slave_m0_writedata),                    //  output,  width = 32,                               .writedata
		.cxl_io_slave_m0_address                      (cxl_io_slave_m0_address),                      //  output,  width = 24,                               .address
		.cxl_io_slave_m0_write                        (cxl_io_slave_m0_write),                        //  output,   width = 1,                               .write
		.cxl_io_slave_m0_read                         (cxl_io_slave_m0_read),                         //  output,   width = 1,                               .read
		.cxl_io_slave_m0_byteenable                   (cxl_io_slave_m0_byteenable),                   //  output,   width = 4,                               .byteenable
		.cxl_io_slave_m0_debugaccess                  (cxl_io_slave_m0_debugaccess),                  //  output,   width = 1,                               .debugaccess
		.cmb2avst_slave_m0_waitrequest                (cmb2avst_slave_m0_waitrequest),                //   input,   width = 1,              cmb2avst_slave_m0.waitrequest
		.cmb2avst_slave_m0_readdata                   (cmb2avst_slave_m0_readdata),                   //   input,  width = 32,                               .readdata
		.cmb2avst_slave_m0_readdatavalid              (cmb2avst_slave_m0_readdatavalid),              //   input,   width = 1,                               .readdatavalid
		.cmb2avst_slave_m0_burstcount                 (cmb2avst_slave_m0_burstcount),                 //  output,   width = 1,                               .burstcount
		.cmb2avst_slave_m0_writedata                  (cmb2avst_slave_m0_writedata),                  //  output,  width = 32,                               .writedata
		.cmb2avst_slave_m0_address                    (cmb2avst_slave_m0_address),                    //  output,  width = 24,                               .address
		.cmb2avst_slave_m0_write                      (cmb2avst_slave_m0_write),                      //  output,   width = 1,                               .write
		.cmb2avst_slave_m0_read                       (cmb2avst_slave_m0_read),                       //  output,   width = 1,                               .read
		.cmb2avst_slave_m0_byteenable                 (cmb2avst_slave_m0_byteenable),                 //  output,   width = 4,                               .byteenable
		.cmb2avst_slave_m0_debugaccess                (cmb2avst_slave_m0_debugaccess),                //  output,   width = 1,                               .debugaccess
		.debug_master_s0_waitrequest                  (debug_master_s0_waitrequest),                  //  output,   width = 1,                debug_master_s0.waitrequest
		.debug_master_s0_readdata                     (debug_master_s0_readdata),                     //  output,  width = 32,                               .readdata
		.debug_master_s0_readdatavalid                (debug_master_s0_readdatavalid),                //  output,   width = 1,                               .readdatavalid
		.debug_master_s0_burstcount                   (debug_master_s0_burstcount),                   //   input,   width = 1,                               .burstcount
		.debug_master_s0_writedata                    (debug_master_s0_writedata),                    //   input,  width = 32,                               .writedata
		.debug_master_s0_address                      (debug_master_s0_address),                      //   input,  width = 32,                               .address
		.debug_master_s0_write                        (debug_master_s0_write),                        //   input,   width = 1,                               .write
		.debug_master_s0_read                         (debug_master_s0_read),                         //   input,   width = 1,                               .read
		.debug_master_s0_byteenable                   (debug_master_s0_byteenable),                   //   input,   width = 4,                               .byteenable
		.debug_master_s0_debugaccess                  (debug_master_s0_debugaccess),                  //   input,   width = 1,                               .debugaccess
		.side_clock_hip_clk                           (side_clock_hip_clk),                           //   input,   width = 1,                 side_clock_hip.clk
		.side_reset_hip_reset_n                       (side_reset_hip_reset_n),                       //   input,   width = 1,                 side_reset_hip.reset_n
		.hip_reconfig_slave_m0_waitrequest            (hip_reconfig_slave_m0_waitrequest),            //   input,   width = 1,          hip_reconfig_slave_m0.waitrequest
		.hip_reconfig_slave_m0_readdata               (hip_reconfig_slave_m0_readdata),               //   input,   width = 8,                               .readdata
		.hip_reconfig_slave_m0_readdatavalid          (hip_reconfig_slave_m0_readdatavalid),          //   input,   width = 1,                               .readdatavalid
		.hip_reconfig_slave_m0_burstcount             (hip_reconfig_slave_m0_burstcount),             //  output,   width = 1,                               .burstcount
		.hip_reconfig_slave_m0_writedata              (hip_reconfig_slave_m0_writedata),              //  output,   width = 8,                               .writedata
		.hip_reconfig_slave_m0_address                (hip_reconfig_slave_m0_address),                //  output,  width = 24,                               .address
		.hip_reconfig_slave_m0_write                  (hip_reconfig_slave_m0_write),                  //  output,   width = 1,                               .write
		.hip_reconfig_slave_m0_read                   (hip_reconfig_slave_m0_read),                   //  output,   width = 1,                               .read
		.hip_reconfig_slave_m0_byteenable             (hip_reconfig_slave_m0_byteenable),             //  output,   width = 1,                               .byteenable
		.hip_reconfig_slave_m0_debugaccess            (hip_reconfig_slave_m0_debugaccess),            //  output,   width = 1,                               .debugaccess
		.usr_avmm_hip_reconfig_slave_m0_waitrequest   (usr_avmm_hip_reconfig_slave_m0_waitrequest),   //   input,   width = 1, usr_avmm_hip_reconfig_slave_m0.waitrequest
		.usr_avmm_hip_reconfig_slave_m0_readdata      (usr_avmm_hip_reconfig_slave_m0_readdata),      //   input,   width = 8,                               .readdata
		.usr_avmm_hip_reconfig_slave_m0_readdatavalid (usr_avmm_hip_reconfig_slave_m0_readdatavalid), //   input,   width = 1,                               .readdatavalid
		.usr_avmm_hip_reconfig_slave_m0_burstcount    (usr_avmm_hip_reconfig_slave_m0_burstcount),    //  output,   width = 1,                               .burstcount
		.usr_avmm_hip_reconfig_slave_m0_writedata     (usr_avmm_hip_reconfig_slave_m0_writedata),     //  output,   width = 8,                               .writedata
		.usr_avmm_hip_reconfig_slave_m0_address       (usr_avmm_hip_reconfig_slave_m0_address),       //  output,  width = 24,                               .address
		.usr_avmm_hip_reconfig_slave_m0_write         (usr_avmm_hip_reconfig_slave_m0_write),         //  output,   width = 1,                               .write
		.usr_avmm_hip_reconfig_slave_m0_read          (usr_avmm_hip_reconfig_slave_m0_read),          //  output,   width = 1,                               .read
		.usr_avmm_hip_reconfig_slave_m0_byteenable    (usr_avmm_hip_reconfig_slave_m0_byteenable),    //  output,   width = 1,                               .byteenable
		.usr_avmm_hip_reconfig_slave_m0_debugaccess   (usr_avmm_hip_reconfig_slave_m0_debugaccess),   //  output,   width = 1,                               .debugaccess
		.cxl_compliance_slave_m0_waitrequest          (cxl_compliance_slave_m0_waitrequest),          //   input,   width = 1,        cxl_compliance_slave_m0.waitrequest
		.cxl_compliance_slave_m0_readdata             (cxl_compliance_slave_m0_readdata),             //   input,  width = 64,                               .readdata
		.cxl_compliance_slave_m0_readdatavalid        (cxl_compliance_slave_m0_readdatavalid),        //   input,   width = 1,                               .readdatavalid
		.cxl_compliance_slave_m0_burstcount           (cxl_compliance_slave_m0_burstcount),           //  output,   width = 1,                               .burstcount
		.cxl_compliance_slave_m0_writedata            (cxl_compliance_slave_m0_writedata),            //  output,  width = 64,                               .writedata
		.cxl_compliance_slave_m0_address              (cxl_compliance_slave_m0_address),              //  output,  width = 24,                               .address
		.cxl_compliance_slave_m0_write                (cxl_compliance_slave_m0_write),                //  output,   width = 1,                               .write
		.cxl_compliance_slave_m0_read                 (cxl_compliance_slave_m0_read),                 //  output,   width = 1,                               .read
		.cxl_compliance_slave_m0_byteenable           (cxl_compliance_slave_m0_byteenable),           //  output,   width = 8,                               .byteenable
		.cxl_compliance_slave_m0_debugaccess          (cxl_compliance_slave_m0_debugaccess)           //  output,   width = 1,                               .debugaccess
	);

endmodule
