# (C) 2001-2022 Intel Corporation. All rights reserved.
# Your use of Intel Corporation's design tools, logic functions and other 
# software and tools, and its AMPP partner logic functions, and any output 
# files from any of the foregoing (including device programming or simulation 
# files), and any associated documentation or information are expressly subject 
# to the terms and conditions of the Intel Program License Subscription 
# Agreement, Intel FPGA IP License Agreement, or other applicable 
# license agreement, including, without limitation, that your use is for the 
# sole purpose of programming logic devices manufactured by Intel and sold by 
# Intel or its authorized distributors.  Please refer to the applicable 
# agreement for further details.


## Used for Example design on Devkit RNR-A0##


# reset interface
set_location_assignment PIN_CD58 -to resetn
set_instance_assignment -name IO_STANDARD "1.0 V" -to resetn

# fabric PLL refclk
set_location_assignment PIN_AN61 -to refclk4
#set_instance_assignment -name IO_STANDARD "1.2 V" -to refclk4
set_instance_assignment -name IO_STANDARD "TRUE DIFFERENTIAL SIGNALING" -to refclk4

# refclk interface
set_location_assignment PIN_DR68 -to refclk0
set_instance_assignment -name IO_STANDARD HCSL -to refclk0
set_location_assignment PIN_CU68 -to refclk1
set_instance_assignment -name IO_STANDARD HCSL -to refclk1

# CXT TX Pin assignments
set_location_assignment PIN_DH73 -to cxl_tx_n[0]
set_location_assignment PIN_DE76 -to cxl_tx_n[1]
set_location_assignment PIN_CT73 -to cxl_tx_n[2]
set_location_assignment PIN_CM76 -to cxl_tx_n[3]
set_location_assignment PIN_CC73 -to cxl_tx_n[4]
set_location_assignment PIN_BY76 -to cxl_tx_n[5]
set_location_assignment PIN_BL73 -to cxl_tx_n[6]
set_location_assignment PIN_BH76 -to cxl_tx_n[7]
set_location_assignment PIN_AW73 -to cxl_tx_n[8]
set_location_assignment PIN_AR76 -to cxl_tx_n[9]
set_location_assignment PIN_AF73 -to cxl_tx_n[10]
set_location_assignment PIN_AC76 -to cxl_tx_n[11]
set_location_assignment PIN_T73 -to cxl_tx_n[12]
set_location_assignment PIN_G73 -to cxl_tx_n[13]
set_location_assignment PIN_E69 -to cxl_tx_n[14]
set_location_assignment PIN_P69 -to cxl_tx_n[15]
set_location_assignment PIN_DL74 -to cxl_tx_p[0]
set_location_assignment PIN_DB77 -to cxl_tx_p[1]
set_location_assignment PIN_CW74 -to cxl_tx_p[2]
set_location_assignment PIN_CJ77 -to cxl_tx_p[3]
set_location_assignment PIN_CF74 -to cxl_tx_p[4]
set_location_assignment PIN_BU77 -to cxl_tx_p[5]
set_location_assignment PIN_BP74 -to cxl_tx_p[6]
set_location_assignment PIN_BE77 -to cxl_tx_p[7]
set_location_assignment PIN_BB74 -to cxl_tx_p[8]
set_location_assignment PIN_AM77 -to cxl_tx_p[9]
set_location_assignment PIN_AJ74 -to cxl_tx_p[10]
set_location_assignment PIN_Y77 -to cxl_tx_p[11]
set_location_assignment PIN_V74 -to cxl_tx_p[12]
set_location_assignment PIN_K74 -to cxl_tx_p[13]
set_location_assignment PIN_C71 -to cxl_tx_p[14]
set_location_assignment PIN_M71 -to cxl_tx_p[15]
set_instance_assignment -name IO_STANDARD "HIGH SPEED DIFFERENTIAL I/O" -to cxl_tx_n[*]
set_instance_assignment -name IO_STANDARD "HIGH SPEED DIFFERENTIAL I/O" -to cxl_tx_p[*]

# CXT RX Pin assignments
set_location_assignment PIN_DB83 -to cxl_rx_n[0]
set_location_assignment PIN_CT79 -to cxl_rx_n[1]
set_location_assignment PIN_CJ83 -to cxl_rx_n[2]
set_location_assignment PIN_CC79 -to cxl_rx_n[3]
set_location_assignment PIN_BU83 -to cxl_rx_n[4]
set_location_assignment PIN_BL79 -to cxl_rx_n[5]
set_location_assignment PIN_BE83 -to cxl_rx_n[6]
set_location_assignment PIN_AW79 -to cxl_rx_n[7]
set_location_assignment PIN_AM83 -to cxl_rx_n[8]
set_location_assignment PIN_AF79 -to cxl_rx_n[9]
set_location_assignment PIN_Y83 -to cxl_rx_n[10]
set_location_assignment PIN_T79 -to cxl_rx_n[11]
set_location_assignment PIN_M83 -to cxl_rx_n[12]
set_location_assignment PIN_G79 -to cxl_rx_n[13]
set_location_assignment PIN_P76 -to cxl_rx_n[14]
set_location_assignment PIN_E76 -to cxl_rx_n[15]
set_location_assignment PIN_DE82 -to cxl_rx_p[0]
set_location_assignment PIN_CW80 -to cxl_rx_p[1]
set_location_assignment PIN_CM82 -to cxl_rx_p[2]
set_location_assignment PIN_CF80 -to cxl_rx_p[3]
set_location_assignment PIN_BY82 -to cxl_rx_p[4]
set_location_assignment PIN_BP80 -to cxl_rx_p[5]
set_location_assignment PIN_BH82 -to cxl_rx_p[6]
set_location_assignment PIN_BB80 -to cxl_rx_p[7]
set_location_assignment PIN_AR82 -to cxl_rx_p[8]
set_location_assignment PIN_AJ80 -to cxl_rx_p[9]
set_location_assignment PIN_AC82 -to cxl_rx_p[10]
set_location_assignment PIN_V80 -to cxl_rx_p[11]
set_location_assignment PIN_P82 -to cxl_rx_p[12]
set_location_assignment PIN_K80 -to cxl_rx_p[13]
set_location_assignment PIN_M77 -to cxl_rx_p[14]
set_location_assignment PIN_C77 -to cxl_rx_p[15]
set_instance_assignment -name IO_STANDARD "HIGH SPEED DIFFERENTIAL I/O" -to cxl_rx_n[*]
set_instance_assignment -name IO_STANDARD "HIGH SPEED DIFFERENTIAL I/O" -to cxl_rx_p[*]
set_location_assignment PIN_MA44 -to mem_refclk[0]
set_instance_assignment -name IO_STANDARD "TRUE DIFFERENTIAL SIGNALING" -to mem_refclk[0] -entity ddr4
set_location_assignment PIN_LH48 -to mem_ck[0][0]
set_instance_assignment -name IO_STANDARD "DIFFERENTIAL 1.2-V SSTL" -to mem_ck[0][0]
set_location_assignment PIN_LL49 -to mem_ck_n[0][0]
set_instance_assignment -name IO_STANDARD "DIFFERENTIAL 1.2-V SSTL" -to mem_ck_n[0][0]
set_location_assignment PIN_LH44 -to mem_bg[0][1]
set_location_assignment PIN_LR47 -to mem_bg[0][0]
set_instance_assignment -name IO_STANDARD "SSTL-12" -to mem_bg[0][*]
set_location_assignment PIN_LN48 -to mem_ba[0][1]
set_location_assignment PIN_LW47 -to mem_ba[0][0]
set_instance_assignment -name IO_STANDARD "SSTL-12" -to mem_ba[0][*]
set_location_assignment PIN_MA48 -to mem_alert_n[0]
set_location_assignment PIN_LN44 -to mem_oct_rzqin[0]
set_location_assignment PIN_LB48 -to mem_par[0]
set_instance_assignment -name IO_STANDARD "SSTL-12" -to mem_par[0]
set_location_assignment PIN_LB46 -to mem_cke[0][0]
set_instance_assignment -name IO_STANDARD "SSTL-12" -to mem_cke[0][0]
set_location_assignment PIN_LH46 -to mem_odt[0][0]
set_instance_assignment -name IO_STANDARD "SSTL-12" -to mem_odt[0][0]
set_location_assignment PIN_KW45 -to mem_act_n[0]
set_instance_assignment -name IO_STANDARD "SSTL-12" -to mem_act_n[0]
set_location_assignment PIN_LB44 -to mem_cs_n[0][0]
set_instance_assignment -name IO_STANDARD "SSTL-12" -to mem_cs_n[0][0]
set_location_assignment PIN_LL45 -to mem_reset_n[0]
set_location_assignment PIN_LN46 -to mem_a[0][16]
set_location_assignment PIN_LR45 -to mem_a[0][15]
set_location_assignment PIN_MA46 -to mem_a[0][14]
set_location_assignment PIN_LW45 -to mem_a[0][13]
set_location_assignment PIN_LR43 -to mem_a[0][12]
set_location_assignment PIN_KJ49 -to mem_a[0][11]
set_location_assignment PIN_KF48 -to mem_a[0][10]
set_location_assignment PIN_KU48 -to mem_a[0][9]
set_location_assignment PIN_KR49 -to mem_a[0][8]
set_location_assignment PIN_KJ47 -to mem_a[0][7]
set_location_assignment PIN_KF46 -to mem_a[0][6]
set_location_assignment PIN_KR47 -to mem_a[0][5]
set_location_assignment PIN_KU46 -to mem_a[0][4]
set_location_assignment PIN_KF44 -to mem_a[0][3]
set_location_assignment PIN_KJ45 -to mem_a[0][2]
set_location_assignment PIN_KU44 -to mem_a[0][1]
set_location_assignment PIN_KR45 -to mem_a[0][0]
set_instance_assignment -name IO_STANDARD "SSTL-12" -to mem_a[0][*]
set_location_assignment PIN_LN60 -to mem_dq[0][71]
set_location_assignment PIN_LR55 -to mem_dq[0][70]
set_location_assignment PIN_LR59 -to mem_dq[0][69]
set_location_assignment PIN_LW55 -to mem_dq[0][68]
set_location_assignment PIN_MA60 -to mem_dq[0][67]
set_location_assignment PIN_LN56 -to mem_dq[0][66]
set_location_assignment PIN_LW59 -to mem_dq[0][65]
set_location_assignment PIN_MA56 -to mem_dq[0][64]
set_location_assignment PIN_MC57 -to mem_dq[0][63]
set_location_assignment PIN_MD52 -to mem_dq[0][62]
set_location_assignment PIN_MK57 -to mem_dq[0][61]
set_location_assignment PIN_MH52 -to mem_dq[0][60]
set_location_assignment PIN_MH56 -to mem_dq[0][59]
set_location_assignment PIN_MC53 -to mem_dq[0][58]
set_location_assignment PIN_MD56 -to mem_dq[0][57]
set_location_assignment PIN_MK53 -to mem_dq[0][56]
set_location_assignment PIN_MC63 -to mem_dq[0][55]
set_location_assignment PIN_MD58 -to mem_dq[0][54]
set_location_assignment PIN_MK63 -to mem_dq[0][53]
set_location_assignment PIN_MH58 -to mem_dq[0][52]
set_location_assignment PIN_MD62 -to mem_dq[0][51]
set_location_assignment PIN_MK59 -to mem_dq[0][50]
set_location_assignment PIN_MH62 -to mem_dq[0][49]
set_location_assignment PIN_MC59 -to mem_dq[0][48]
set_location_assignment PIN_KW55 -to mem_dq[0][47]
set_location_assignment PIN_LB50 -to mem_dq[0][46]
set_location_assignment PIN_LB54 -to mem_dq[0][45]
set_location_assignment PIN_LH50 -to mem_dq[0][44]
set_location_assignment PIN_LH54 -to mem_dq[0][43]
set_location_assignment PIN_KW51 -to mem_dq[0][42]
set_location_assignment PIN_LL55 -to mem_dq[0][41]
set_location_assignment PIN_LL51 -to mem_dq[0][40]
set_location_assignment PIN_LN54 -to mem_dq[0][39]
set_location_assignment PIN_LR49 -to mem_dq[0][38]
set_location_assignment PIN_LR53 -to mem_dq[0][37]
set_location_assignment PIN_LN50 -to mem_dq[0][36]
set_location_assignment PIN_MA54 -to mem_dq[0][35]
set_location_assignment PIN_MA50 -to mem_dq[0][34]
set_location_assignment PIN_LW53 -to mem_dq[0][33]
set_location_assignment PIN_LW49 -to mem_dq[0][32]
set_location_assignment PIN_MC45 -to mem_dq[0][31]
set_location_assignment PIN_MD40 -to mem_dq[0][30]
set_location_assignment PIN_MK45 -to mem_dq[0][29]
set_location_assignment PIN_MH40 -to mem_dq[0][28]
set_location_assignment PIN_MH44 -to mem_dq[0][27]
set_location_assignment PIN_MC41 -to mem_dq[0][26]
set_location_assignment PIN_MD44 -to mem_dq[0][25]
set_location_assignment PIN_MK41 -to mem_dq[0][24]
set_location_assignment PIN_MC51 -to mem_dq[0][23]
set_location_assignment PIN_MD46 -to mem_dq[0][22]
set_location_assignment PIN_MK51 -to mem_dq[0][21]
set_location_assignment PIN_MH46 -to mem_dq[0][20]
set_location_assignment PIN_MD50 -to mem_dq[0][19]
set_location_assignment PIN_MK47 -to mem_dq[0][18]
set_location_assignment PIN_MH50 -to mem_dq[0][17]
set_location_assignment PIN_MC47 -to mem_dq[0][16]
set_location_assignment PIN_LN42 -to mem_dq[0][15]
set_location_assignment PIN_LR37 -to mem_dq[0][14]
set_location_assignment PIN_LR41 -to mem_dq[0][13]
set_location_assignment PIN_LW37 -to mem_dq[0][12]
set_location_assignment PIN_LW41 -to mem_dq[0][11]
set_location_assignment PIN_LN38 -to mem_dq[0][10]
set_location_assignment PIN_MA42 -to mem_dq[0][9]
set_location_assignment PIN_MA38 -to mem_dq[0][8]
set_location_assignment PIN_MC39 -to mem_dq[0][7]
set_location_assignment PIN_MD34 -to mem_dq[0][6]
set_location_assignment PIN_MK39 -to mem_dq[0][5]
set_location_assignment PIN_MH34 -to mem_dq[0][4]
set_location_assignment PIN_MD38 -to mem_dq[0][3]
set_location_assignment PIN_MK35 -to mem_dq[0][2]
set_location_assignment PIN_MH38 -to mem_dq[0][1]
set_location_assignment PIN_MC35 -to mem_dq[0][0]
set_instance_assignment -name IO_STANDARD "1.2-V POD" -to mem_dq[0][*]
set_location_assignment PIN_LW57 -to mem_dqs[0][8]
set_location_assignment PIN_MH54 -to mem_dqs[0][7]
set_location_assignment PIN_MH60 -to mem_dqs[0][6]
set_location_assignment PIN_LH52 -to mem_dqs[0][5]
set_location_assignment PIN_LW51 -to mem_dqs[0][4]
set_location_assignment PIN_MH42 -to mem_dqs[0][3]
set_location_assignment PIN_MH48 -to mem_dqs[0][2]
set_location_assignment PIN_LW39 -to mem_dqs[0][1]
set_location_assignment PIN_MH36 -to mem_dqs[0][0]
set_instance_assignment -name IO_STANDARD "DIFFERENTIAL 1.2-V POD" -to mem_dqs[0][*]
set_location_assignment PIN_MA58 -to mem_dqs_n[0][8]
set_location_assignment PIN_MK55 -to mem_dqs_n[0][7]
set_location_assignment PIN_MK61 -to mem_dqs_n[0][6]
set_location_assignment PIN_LL53 -to mem_dqs_n[0][5]
set_location_assignment PIN_MA52 -to mem_dqs_n[0][4]
set_location_assignment PIN_MK43 -to mem_dqs_n[0][3]
set_location_assignment PIN_MK49 -to mem_dqs_n[0][2]
set_location_assignment PIN_MA40 -to mem_dqs_n[0][1]
set_location_assignment PIN_MK37 -to mem_dqs_n[0][0]
set_instance_assignment -name IO_STANDARD "DIFFERENTIAL 1.2-V POD" -to mem_dqs_n[0][*]
set_location_assignment PIN_LR57 -to mem_dbi_n[0][8]
set_location_assignment PIN_MD54 -to mem_dbi_n[0][7]
set_location_assignment PIN_MD60 -to mem_dbi_n[0][6]
set_location_assignment PIN_LB52 -to mem_dbi_n[0][5]
set_location_assignment PIN_LR51 -to mem_dbi_n[0][4]
set_location_assignment PIN_MD42 -to mem_dbi_n[0][3]
set_location_assignment PIN_MD48 -to mem_dbi_n[0][2]
set_location_assignment PIN_LR39 -to mem_dbi_n[0][1]
set_location_assignment PIN_MD36 -to mem_dbi_n[0][0]
set_instance_assignment -name IO_STANDARD "1.2-V POD" -to mem_dbi_n[0][*]

#-------DDR4 COMP CH1 PIN ASSIGNMENT--------# 
set_location_assignment PIN_KU36 -to mem_refclk[1]
set_instance_assignment -name IO_STANDARD "TRUE DIFFERENTIAL SIGNALING" -to mem_refclk[1] -entity ddr4
set_location_assignment PIN_KR39 -to mem_ck[1][0]
set_instance_assignment -name IO_STANDARD "DIFFERENTIAL 1.2-V SSTL" -to mem_ck[1][0]
set_location_assignment PIN_KU38 -to mem_ck_n[1][0]
set_instance_assignment -name IO_STANDARD "DIFFERENTIAL 1.2-V SSTL" -to mem_ck_n[1][0]
set_location_assignment PIN_KR43 -to mem_bg[1][1]
set_location_assignment PIN_KF32 -to mem_bg[1][0]
set_instance_assignment -name IO_STANDARD "SSTL-12" -to mem_bg[1][*]
set_location_assignment PIN_KJ33 -to mem_ba[1][1]
set_location_assignment PIN_KR33 -to mem_ba[1][0]
set_instance_assignment -name IO_STANDARD "SSTL-12" -to mem_ba[1][*]
set_location_assignment PIN_KU32 -to mem_alert_n[1]
set_location_assignment PIN_KJ37 -to mem_oct_rzqin[1]
set_location_assignment PIN_KJ39 -to mem_par[1]
set_instance_assignment -name IO_STANDARD "SSTL-12" -to mem_par[1]
set_location_assignment PIN_KF40 -to mem_cke[1][0]
set_instance_assignment -name IO_STANDARD "SSTL-12" -to mem_cke[1][0]
set_location_assignment PIN_KU40 -to mem_odt[1][0]
set_instance_assignment -name IO_STANDARD "SSTL-12" -to mem_odt[1][0]
set_location_assignment PIN_KJ43 -to mem_act_n[1]
set_instance_assignment -name IO_STANDARD "SSTL-12" -to mem_act_n[1]
set_location_assignment PIN_KF42 -to mem_cs_n[1][0]
set_instance_assignment -name IO_STANDARD "SSTL-12" -to mem_cs_n[1][0]
set_location_assignment PIN_KU42 -to mem_reset_n[1]
set_location_assignment PIN_KJ35 -to mem_a[1][16]
set_location_assignment PIN_KF34 -to mem_a[1][15]
set_location_assignment PIN_KR35 -to mem_a[1][14]
set_location_assignment PIN_KU34 -to mem_a[1][13]
set_location_assignment PIN_KF36 -to mem_a[1][12]
set_location_assignment PIN_LB38 -to mem_a[1][11]
set_location_assignment PIN_KW39 -to mem_a[1][10]
set_location_assignment PIN_LL39 -to mem_a[1][9]
set_location_assignment PIN_LH38 -to mem_a[1][8]
set_location_assignment PIN_KW41 -to mem_a[1][7]
set_location_assignment PIN_LB40 -to mem_a[1][6]
set_location_assignment PIN_LL41 -to mem_a[1][5]
set_location_assignment PIN_LH40 -to mem_a[1][4]
set_location_assignment PIN_LB42 -to mem_a[1][3]
set_location_assignment PIN_KW43 -to mem_a[1][2]
set_location_assignment PIN_LL43 -to mem_a[1][1]
set_location_assignment PIN_LH42 -to mem_a[1][0]
set_instance_assignment -name IO_STANDARD "SSTL-12" -to mem_a[1][*]
set_location_assignment PIN_LU4 -to mem_dq[1][71]
set_location_assignment PIN_LN11 -to mem_dq[1][70]
set_location_assignment PIN_MC5 -to mem_dq[1][69]
set_location_assignment PIN_MA11 -to mem_dq[1][68]
set_location_assignment PIN_LW2 -to mem_dq[1][67]
set_location_assignment PIN_LW9 -to mem_dq[1][66]
set_location_assignment PIN_MA4 -to mem_dq[1][65]
set_location_assignment PIN_LR9 -to mem_dq[1][64]
set_location_assignment PIN_LN23 -to mem_dq[1][63]
set_location_assignment PIN_MA15 -to mem_dq[1][62]
set_location_assignment PIN_MA23 -to mem_dq[1][61]
set_location_assignment PIN_LN15 -to mem_dq[1][60]
set_location_assignment PIN_LR21 -to mem_dq[1][59]
set_location_assignment PIN_LW13 -to mem_dq[1][58]
set_location_assignment PIN_LW21 -to mem_dq[1][57]
set_location_assignment PIN_LR13 -to mem_dq[1][56]
set_location_assignment PIN_MC17 -to mem_dq[1][55]
set_location_assignment PIN_MF5 -to mem_dq[1][54]
set_location_assignment PIN_MK17 -to mem_dq[1][53]
set_location_assignment PIN_MD7 -to mem_dq[1][52]
set_location_assignment PIN_MD15 -to mem_dq[1][51]
set_location_assignment PIN_MC9 -to mem_dq[1][50]
set_location_assignment PIN_MH15 -to mem_dq[1][49]
set_location_assignment PIN_MH7 -to mem_dq[1][48]
set_location_assignment PIN_MA30 -to mem_dq[1][47]
set_location_assignment PIN_MA26 -to mem_dq[1][46]
set_location_assignment PIN_LN30 -to mem_dq[1][45]
set_location_assignment PIN_LR25 -to mem_dq[1][44]
set_location_assignment PIN_LR29 -to mem_dq[1][43]
set_location_assignment PIN_LW25 -to mem_dq[1][42]
set_location_assignment PIN_LW29 -to mem_dq[1][41]
set_location_assignment PIN_LN26 -to mem_dq[1][40]
set_location_assignment PIN_JL37 -to mem_dq[1][39]
set_location_assignment PIN_JL33 -to mem_dq[1][38]
set_location_assignment PIN_JP36 -to mem_dq[1][37]
set_location_assignment PIN_JP32 -to mem_dq[1][36]
set_location_assignment PIN_KC37 -to mem_dq[1][35]
set_location_assignment PIN_KC33 -to mem_dq[1][34]
set_location_assignment PIN_JY36 -to mem_dq[1][33]
set_location_assignment PIN_JY32 -to mem_dq[1][32]
set_location_assignment PIN_LB36 -to mem_dq[1][31]
set_location_assignment PIN_KW37 -to mem_dq[1][30]
set_location_assignment PIN_LL37 -to mem_dq[1][29]
set_location_assignment PIN_LB32 -to mem_dq[1][28]
set_location_assignment PIN_LH36 -to mem_dq[1][27]
set_location_assignment PIN_LL33 -to mem_dq[1][26]
set_location_assignment PIN_KW33 -to mem_dq[1][25]
set_location_assignment PIN_LH32 -to mem_dq[1][24]
set_location_assignment PIN_MC27 -to mem_dq[1][23]
set_location_assignment PIN_MC21 -to mem_dq[1][22]
set_location_assignment PIN_MK27 -to mem_dq[1][21]
set_location_assignment PIN_MD19 -to mem_dq[1][20]
set_location_assignment PIN_MD26 -to mem_dq[1][19]
set_location_assignment PIN_MK21 -to mem_dq[1][18]
set_location_assignment PIN_MH26 -to mem_dq[1][17]
set_location_assignment PIN_MH19 -to mem_dq[1][16]
set_location_assignment PIN_MA36 -to mem_dq[1][15]
set_location_assignment PIN_MA32 -to mem_dq[1][14]
set_location_assignment PIN_LN36 -to mem_dq[1][13]
set_location_assignment PIN_LR31 -to mem_dq[1][12]
set_location_assignment PIN_LR35 -to mem_dq[1][11]
set_location_assignment PIN_LW31 -to mem_dq[1][10]
set_location_assignment PIN_LW35 -to mem_dq[1][9]
set_location_assignment PIN_LN32 -to mem_dq[1][8]
set_location_assignment PIN_MC33 -to mem_dq[1][7]
set_location_assignment PIN_MD28 -to mem_dq[1][6]
set_location_assignment PIN_MK33 -to mem_dq[1][5]
set_location_assignment PIN_MH28 -to mem_dq[1][4]
set_location_assignment PIN_MD32 -to mem_dq[1][3]
set_location_assignment PIN_MK29 -to mem_dq[1][2]
set_location_assignment PIN_MH32 -to mem_dq[1][1]
set_location_assignment PIN_MC29 -to mem_dq[1][0]
set_location_assignment PIN_LW5 -to mem_dqs[1][8]
set_location_assignment PIN_LW17 -to mem_dqs[1][7]
set_location_assignment PIN_MH11 -to mem_dqs[1][6]
set_location_assignment PIN_LW27 -to mem_dqs[1][5]
set_location_assignment PIN_JY34 -to mem_dqs[1][4]
set_location_assignment PIN_LH34 -to mem_dqs[1][3]
set_location_assignment PIN_MH23 -to mem_dqs[1][2]
set_location_assignment PIN_LW33 -to mem_dqs[1][1]
set_location_assignment PIN_MH30 -to mem_dqs[1][0]
set_instance_assignment -name IO_STANDARD "DIFFERENTIAL 1.2-V POD" -to mem_dqs[1][*]
set_location_assignment PIN_MA7 -to mem_dqs_n[1][8]
set_location_assignment PIN_MA19 -to mem_dqs_n[1][7]
set_location_assignment PIN_MK13 -to mem_dqs_n[1][6]
set_location_assignment PIN_MA28 -to mem_dqs_n[1][5]
set_location_assignment PIN_KC35 -to mem_dqs_n[1][4]
set_location_assignment PIN_LL35 -to mem_dqs_n[1][3]
set_location_assignment PIN_MK25 -to mem_dqs_n[1][2]
set_location_assignment PIN_MA34 -to mem_dqs_n[1][1]
set_location_assignment PIN_MK31 -to mem_dqs_n[1][0]
set_instance_assignment -name IO_STANDARD "DIFFERENTIAL 1.2-V POD" -to mem_dqs_n[1][*]
set_location_assignment PIN_LR5 -to mem_dbi_n[1][8]
set_location_assignment PIN_LR17 -to mem_dbi_n[1][7]
set_location_assignment PIN_MD11 -to mem_dbi_n[1][6]
set_location_assignment PIN_LR27 -to mem_dbi_n[1][5]
set_location_assignment PIN_JP34 -to mem_dbi_n[1][4]
set_location_assignment PIN_LB34 -to mem_dbi_n[1][3]
set_location_assignment PIN_MD23 -to mem_dbi_n[1][2]
set_location_assignment PIN_LR33 -to mem_dbi_n[1][1]
set_location_assignment PIN_MD30 -to mem_dbi_n[1][0]
set_instance_assignment -name IO_STANDARD "1.2-V POD" -to mem_dbi_n[1][*]
